### ISSUE TITLE
Организационный тикет:

### ISSUE THREAD

**Issue by SirSerje** [romanmtb/Site#4]
На примере твоего репозитория мы попытаемся с тобой поработать, как это делают большинство разработчиков: есть репозиторий, мы в него вливаем, делаем правки, тестируем и потихоньку прокачиваем скилл.

**Создай**:
1. тикет "изменить readme file" и назначь меня исполнителем - это чтобы с задачами въехать быстрее как работать, а я впишу документацию небольшую.
2. по своем желанию размести labels на задачи, можешь создать свои (короткие на английском)
3. создай хотя бы 2 milestone - это временные промежутки, за которые делается ряд задач. Первый будет v.0.1 - в него попадает создание паро-страничного сайта без js, v0.2 - в нее, пускай, попадет немного js и за задачами закрепи, к какому milestone они относятся.

_p.s. если ты все это будешь хорошо понимать, то влиться в рабочий процесс на реальном проекте будет для тебя проще простого;), да, и присвой эту задачу на себя_

**Comment by romanmtb** [comment]
Вроде сделал

**Comment by SirSerje** [comment]
2 и 3 не сделано пока, вот ссылки, где можно отредадактировать.
https://github.com/romanmtb/Site/labels
https://github.com/romanmtb/Site/milestones
