### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by romanmtb** [romanmtb/Site#5]

**Comment by SirSerje** [comment]
Как видишь, если писать номер тикета в названии коммита, автоматически подвяжет в историю по задаче.
Задача не финализирована
**Доделать:** поправить описание, гит операции вынести отдельным пунктом, отформатировать (опционально) примеры

**Comment by SirSerje** [comment]
Вставить в info ссылку на вики, перенести туда инфу по git коммандам
